//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OZMeiCan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public Dish()
        {
            this.DeliverOrderRow = new HashSet<DeliverOrderRow>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> Spiciness { get; set; }
        public int RestaurantId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<DeliverOrderRow> DeliverOrderRow { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
